- disable RPC/NFS (build fails on tirpc linking with default bconds) - disable stack protector   (/busybox-1.35.0/libbb/vfork_daemon_rexec.c:45: undefined reference to `__stack_chk_fail') with uClibc - debug packages are not generated since everything is stripped